DROP TABLE IF EXISTS TBL_ORGANIZATION;
 
CREATE TABLE TBL_ORGANIZATION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  org_title VARCHAR(250) NOT NULL,
  org_description VARCHAR(250) NOT NULL,
  org_location VARCHAR(250) NOT NULL,
  num_volunteers VARCHAR(250) DEFAULT NULL
);