DROP TABLE IF EXISTS TBL_VOLUNTEERS;
DROP TABLE IF EXISTS TBL_ORGANIZATION;
DROP TABLE IF EXISTS TBL_OPPORTUNITIES;
  
CREATE TABLE TBL_VOLUNTEERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  full_name VARCHAR(250) NOT NULL,
  location VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TBL_ORGANIZATION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  location VARCHAR(250) NOT NULL,
  volunteers INT
);

CREATE TABLE TBL_OPPORTUNITIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  description VARCHAR(250) NOT NULL,
  location VARCHAR(250) NOT NULL,
  number_needed INT
);